name:                twit
version:             1.0.0.0
homepage:            https://github.com/hlian/twit-haskell
license:             BSD3
author:              Hao Lian
maintainer:          hao.lian@originate.com
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - containers
  - http-types
  - mtl
  - scotty

executables:
  twit:
    source-dirs:      src
    main:             Main.hs
